### ISSUE TITLE
support for gdal>=3.0.0

### ISSUE THREAD

**Issue by fneum** [FZJ-IEK3-VSA/glaes#5]
Can I ask what is causing the restriction to `gdal<3.0.0`? Would lifting this be an easy fix or much work?

I am currently checking whether we can easily switch over to the upstream `geokit` and `gdal` in PyPSA-Eur:
https://github.com/PyPSA/pypsa-eur/pull/169

We have been using `gdal>=3.0.0` for a few months now after some back and forth:
https://github.com/PyPSA/pypsa-eur/pull/81

There was only one thing regarding the axis mapping strategy which I had to change in the `geokit` fork:
https://github.com/PyPSA/geokit/commit/4c6c98fc8fbae11f44fea46bcdf6299cbf65e0e1

All we use in PyPSA-Eur is running fine when adding this code block and removing the version restriction, but probably there are other use cases where `gdal>=3.0.0` doesn't work?

**Comment by sevberg** [comment]
Hey @fneum, 

TBH I'm not totally sure about what the changes are between gdal 2.XX -> 3.0.0, so I'm also not sure of what changes may be required, nor what the downstream affects may be. But if this (below) is all that was required to adapt things to GDAL>3.0.0, then I don't see any reason to not include it. Would you be interested in making a pull request?

> There was only one thing regarding the axis mapping strategy which I had to change in the geokit fork:
PyPSA/geokit@4c6c98f

I would want to do some testing between gdal 2 & 3 to be sure the behavior is still the same but, assuming it goes well, then I would actually be really happy to remove the "gdal>2.2.0,<3.0.0" restriction in GLAES and RESKit

**Comment by sevberg** [comment]
Short update: I tried adding the line you suggested, which does allow GeoKit (and thus GLAES) to run without problems (yay!). But it also caused a third of my tests in GeoKit to fail (boo!).

So, I will have some sleuthing to do...
